# Generated by Django 5.0.7 on 2025-04-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomacaoNew',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('projeto_nome', models.CharField(max_length=255)),
                ('schema', models.CharField(max_length=255)),
                ('nome_tabela', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Automação New',
                'db_table': '"sustentacao"."automacao_new"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoboNew',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Robo New',
                'db_table': '"sustentacao"."robo_new"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoAutomacao',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação Automação',
                'db_table': '"sustentacao"."situacao_automacao"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarefaNew',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tarefa New',
                'db_table': '"sustentacao"."tarefa_new"',
                'managed': False,
            },
        ),
    ]
