# Generated by Django 5.2 on 2025-05-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_categories', to='categories_app.category')),
                ('id_error', models.ForeignKey(blank=True, db_column='id_error', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_error', to='db.historicotabela')),
            ],
            options={
                'verbose_name': 'Erro Categorizado',
                'verbose_name_plural': 'Erros Categorizados',
                'ordering': ['id'],
            },
        ),
    ]
