# Generated by Django 5.2 on 2025-05-04 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0001_initial'),
        ('db', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcategory',
            name='affected_table',
            field=models.TextField(blank=True, null=True, verbose_name='Tabela Afetada'),
        ),
        migrations.AddField(
            model_name='errorcategory',
            name='description_error',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Erro'),
        ),
        migrations.AddField(
            model_name='errorcategory',
            name='situation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.situacaorotina', verbose_name='Situação Rotina'),
        ),
    ]
