# Generated by Django 5.2 on 2025-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0002_errorcategory_affected_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorcategory',
            old_name='situation_id',
            new_name='situation',
        ),
        migrations.AddField(
            model_name='errorcategory',
            name='date_hour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do registro'),
        ),
    ]
