# Generated by Django 5.2 on 2025-05-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0003_rename_situation_id_errorcategory_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcategory',
            name='routine_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID da Rotina'),
        ),
    ]
