# Generated by Django 5.2 on 2025-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0004_errorcategory_routine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcategory',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Extras'),
        ),
    ]
