# Generated by Django 5.2 on 2025-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0005_errorcategory_extra_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'ordering': ['date_hour'], 'verbose_name': 'Erro Categorizado', 'verbose_name_plural': 'Erros Categorizados'},
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='id_error',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID do erro'),
        ),
    ]
