# Generated by Django 5.2 on 2025-05-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0006_alter_errorcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'verbose_name': 'Erro Categorizado', 'verbose_name_plural': 'Erros Categorizados'},
        ),
        migrations.AddField(
            model_name='category',
            name='requires_description',
            field=models.BooleanField(default=False, verbose_name='Requer Descrição'),
        ),
    ]
