# Generated by Django 5.2 on 2025-05-05 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0007_alter_errorcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcategory',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_categories', to='categories_app.category'),
        ),
    ]
