# Generated by Django 5.2 on 2025-05-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0009_errorcategory_robot_id_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorcategory',
            old_name='robot_id',
            new_name='robot',
        ),
    ]
