# Generated by Django 5.2 on 2025-05-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0010_rename_robot_id_errorcategory_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcategory',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_categories', to='categories_app.category', verbose_name='Categoria   '),
        ),
    ]
