# Generated by Django 5.0.7 on 2025-04-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'ordering': ['name'], 'verbose_name': 'Erro Categorizado', 'verbose_name_plural': 'Erros Categorizados'},
        ),
    ]
